# Netlify configuration for frontend
[build]
  publish = "public"
  base = "/"

[[redirects]]
  from = "/api/*"
  to = "https://qr-1-mrcg.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"